# Desktop Agent System Configuration

# LLM Configuration
llm:
  provider: "vllm"  # options: "ollama", "vllm"
  model: "Qwen/Qwen3-4B-AWQ"
  endpoint: "http://localhost:8000"
  temperature: 0.7
  max_tokens: 4096
  timeout: 60
  
  # vLLM specific settings (when provider is "vllm")
  vllm:
    api_key: null
    served_model_name: null
  
  # Ollama specific settings (when provider is "ollama")
  ollama:
    keep_alive: "5m"

# MCP (Model Context Protocol) Configuration
mcp:
  enabled: true
  servers:
    - name: "file-ops"
      description: "File operations (read, write, delete)"
      command: ["python", "-m", "mcp_file_server"]
      env: {}
      permissions:
        read: true
        write: false  # requires approval
        delete: false  # requires approval
    
    - name: "web-search"
      description: "Web search functionality"
      command: ["python", "-m", "mcp_web_search"]
      env: {}
      permissions:
        read: true
    
    - name: "code-executor"
      description: "Code execution in sandbox"
      command: ["python", "-m", "mcp_code_executor"]
      env: {}
      permissions:
        execute: true

# Sandbox Configuration
sandbox:
  engine: "docker"
  image: "python:3.11-slim"
  timeout: 30
  memory_limit: "512m"
  cpu_limit: "1.0"
  network: false
  volumes:
    - type: "tmpfs"
      source: "/tmp"
      target: "/workspace"
      options: "rw,noexec,nosuid,size=100m"

# Security Configuration
security:
  file_operations:
    require_approval: true
    allowed_extensions: [".txt", ".md", ".json", ".yaml", ".toml", ".py", ".js", ".html", ".css"]
    blocked_paths: ["~/.ssh", "/etc", "/var", "/sys", "/proc"]
  
  code_execution:
    sandbox_only: true
    max_execution_time: 30
    max_output_lines: 100

# Data Storage
storage:
  type: "sqlite"
  path: "data/desktop_agent.db"
  backup:
    enabled: true
    interval: "24h"
    max_backups: 7

# Chat Configuration
chat:
  max_history: 100
  context_window: 8192
  memory:
    enabled: true
    short_term_limit: 50
    long_term_compression: true

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/desktop_agent.log"
  max_size: "10MB"
  backup_count: 5

# CLI Configuration
cli:
  prompt: "Desktop Agent> "
  colors: true
  auto_complete: true
  history_file: "data/.cli_history"

# API Configuration (for future frontend)
api:
  enabled: false
  host: "localhost"
  port: 8000
  cors:
    enabled: true
    origins: ["http://localhost:3000"]